name:                Instant
author:              "Piotr Karpiński"

dependencies:
- base >= 4.7 && < 5
- containers >= 0.6.0.1
- array
- mtl >= 2.2.2
- text
- filepath
- process
- text-format

library:
  source-dirs:
    - src/instant
    - src/parser

executables:
  insc_jvm:
    main:                JvmMain.hs
    source-dirs:         src/main
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is JvmMain
    dependencies:
    - Instant
  insc_llvm:
    main:                LlvmMain.hs
    source-dirs:         src/main
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is LlvmMain
    dependencies:
    - Instant

